data_loader_task:
  description: "Validate and load the CSV file into a DataFrame."
  expected_output: "A pandas DataFrame or an error message if the file is invalid."
  agent: data_loader

inspect_task:
  description: "Inspect the provided sales data and provide schema and data preview."
  expected_output: "A preview of the first few rows and schema information."
  agent: inspector

schema_mapping_task:
  description: "Map the schema of the provided data to a unified schema format."
  expected_output: "A dataframe with a unified schema."
  agent: schema_mapper

schema_validator_task:
  description: "check the source schema with target schema and suggest code changes."
  expected_output: 'alter table syntex for GCP bigquery'
  agent: schema_validator

clean_validate_task:
  description: "Clean and validate the mapped sales data."
  expected_output: "A cleaned and validated dataframe."
  agent: cleaner_validator

code_gen_task:
  description: "Generate Python code to process the sales data."
  expected_output: "Python code (ETL pipeline) for processing the cleaned data."
  agent: code_generator

data_format_check_task:
  description: "compare source dataframe with target dataframe and find the data format difference between them and suggest the code change"
  expected_output: "Python code to parse and convert source data to match target format"
  agent: data_format_validator
